monitor:
  name: ProducerConsumer
  ip: localhost
  maxPermits: 5
  conditionVariablesCount: 2
  algorithm: wjaronski.algorithm.RicardAgrawalaAlgorithm
  proxy:
    pubPort: 6000
    subPort: 6001
    checkIfAliveTime: 500
